### PR TITLE
Initial Comit

### PR DESCRIPTION
**Pull request by nforshifu234dev**

### CODE REVIEW

**Comment by chinojpanda** [comment]
Yayy

**Comment by nforshifu234dev** [comment]
Merge the pull request and view your work.

And hope you realized, stressing me, doesn’t get the work done. T for Tenks
🙂

**Comment by nforshifu234dev** [comment]
Okay. Nigga ion what you have done but atp I have given you a working code
and it seems broke somehow. But okay. Have fun

**Comment by chinojpanda** [comment]
i just did exactly what you said and it stopped working
it wasnt even submitting the inputs

**Pull request merged**
